import { StatusDisponiveisContratacao } from '@pages/shared/models/fluxo.model';

export enum EnumPermissaoStatusContratacao {
  'AdicionarProcessoAdministrativo' = 1,
  'RemoverProcessoAdministrativo' = 2,
  'RemoverAnexo' = 3,
  'AdicionarDotacao' = 4,
  'RemoverDotacao' = 5,
  'AdicionarFornecedorCredenciamento' = 6,
  'RemoverFornecedorCredenciamento' = 7,
  'AdicionarFornecedorDispensa' = 8,
  'RemoverFornecedorDispensa' = 9,
  'AdicionarFornecedorInexgibilidade' = 10,
  'RemoverFornecedorInexgibilidade' = 11,
  'AdicionarFornecedorLicitacao' = 12,
  'RemoverFornecedorLicitacao' = 13,
  'EditarPreco' = 14,
  'DesclassificarFornecedor' = 15,
  'DesclassificarItem' = 16,
  'DesclassificarLote' = 17,
  'AdicionarLote' = 18,
  'RemoverLote' = 19,
  'AdicionarItemLote' = 20,
  'CriarContrato' = 21,
  'VisualizarContrato' = 22,
}

type PermissaoStatusValidaContratacao = Record<StatusDisponiveisContratacao, EnumPermissaoStatusContratacao[]>;

export const PermissaoStatusContratacao: PermissaoStatusValidaContratacao = {
  [StatusDisponiveisContratacao.Aberto]: [
    EnumPermissaoStatusContratacao.AdicionarProcessoAdministrativo,
    EnumPermissaoStatusContratacao.RemoverProcessoAdministrativo,
    EnumPermissaoStatusContratacao.RemoverAnexo,
    EnumPermissaoStatusContratacao.AdicionarDotacao,
    EnumPermissaoStatusContratacao.RemoverDotacao,
    EnumPermissaoStatusContratacao.AdicionarFornecedorCredenciamento,
    EnumPermissaoStatusContratacao.RemoverFornecedorCredenciamento,
    EnumPermissaoStatusContratacao.AdicionarFornecedorDispensa,
    EnumPermissaoStatusContratacao.RemoverFornecedorDispensa,
    EnumPermissaoStatusContratacao.AdicionarFornecedorInexgibilidade,
    EnumPermissaoStatusContratacao.RemoverFornecedorInexgibilidade,
    EnumPermissaoStatusContratacao.AdicionarFornecedorLicitacao,
    EnumPermissaoStatusContratacao.RemoverFornecedorLicitacao,
    EnumPermissaoStatusContratacao.EditarPreco,
    EnumPermissaoStatusContratacao.DesclassificarFornecedor,
    EnumPermissaoStatusContratacao.DesclassificarItem,
    EnumPermissaoStatusContratacao.DesclassificarLote,
    EnumPermissaoStatusContratacao.AdicionarLote,
    EnumPermissaoStatusContratacao.RemoverLote,
    EnumPermissaoStatusContratacao.AdicionarItemLote,
  ],
  [StatusDisponiveisContratacao.Autorizado]: [
    EnumPermissaoStatusContratacao.AdicionarDotacao,
    EnumPermissaoStatusContratacao.RemoverDotacao,
    EnumPermissaoStatusContratacao.AdicionarFornecedorCredenciamento,
    EnumPermissaoStatusContratacao.CriarContrato,
    EnumPermissaoStatusContratacao.VisualizarContrato,
    //EnumPermissaoStatusContratacao.RemoverFornecedorCredenciamento,
    EnumPermissaoStatusContratacao.AdicionarFornecedorDispensa,
    //EnumPermissaoStatusContratacao.RemoverFornecedorDispensa,
    EnumPermissaoStatusContratacao.AdicionarFornecedorInexgibilidade,
    //EnumPermissaoStatusContratacao.RemoverFornecedorInexgibilidade,
    EnumPermissaoStatusContratacao.AdicionarFornecedorLicitacao,
    //EnumPermissaoStatusContratacao.RemoverFornecedorLicitacao,
    EnumPermissaoStatusContratacao.EditarPreco,
    EnumPermissaoStatusContratacao.DesclassificarFornecedor,
    EnumPermissaoStatusContratacao.DesclassificarItem,
    EnumPermissaoStatusContratacao.DesclassificarLote,
  ],
  [StatusDisponiveisContratacao.Cancelado]: [],
  [StatusDisponiveisContratacao.EmAnalise]: [EnumPermissaoStatusContratacao.AdicionarFornecedorCredenciamento],
  [StatusDisponiveisContratacao.Embargado]: [],
  [StatusDisponiveisContratacao.Homologado]: [
    EnumPermissaoStatusContratacao.CriarContrato,
    EnumPermissaoStatusContratacao.VisualizarContrato,
    EnumPermissaoStatusContratacao.DesclassificarItem,
    EnumPermissaoStatusContratacao.AdicionarFornecedorCredenciamento,
    EnumPermissaoStatusContratacao.DesclassificarFornecedor,
  ],
  [StatusDisponiveisContratacao.Concluido]: [
    EnumPermissaoStatusContratacao.CriarContrato,
    EnumPermissaoStatusContratacao.VisualizarContrato,
    EnumPermissaoStatusContratacao.DesclassificarItem,
  ],
};
